### ISSUE TITLE
Use & and | for conjunction and disjunction of search strings instead of , and checkbox

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#15]
Also, add the filter boxes to the table and let column width be decided by the browser.

**Comment by Kogoro** [comment]
Filter boxes are now located in the header of the table and can contain logical expressions with & and |. The mobile version is not searchable at the moment because the header is not displayed in this version.

**Comment by tthuem** [comment]
Seems to work fine. Opened a new issue #17 for the mobile version.
