### ISSUE TITLE
Enable search in the mobile version

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#17]

**Comment by Kogoro** [comment]
Now the search is usable in the mobile version again.

**Comment by tthuem** [comment]
Great! :)

**Comment by tthuem** [comment]
However, I noticed that clicking on a author name does still apply the filter, but does not add the text to the filter box above. Is that desired?

**Comment by Kogoro** [comment]
I changed the layout a bit again and it should be better with less code in the base.

**Comment by tthuem** [comment]
Could you reproduce the problem with clicking on authors?

**Comment by tthuem** [comment]
Works perfect!
