### ISSUE TITLE
Papers found on Google Scholar that have no citations get -2 instead of 0

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#23]
https://scholar.google.de/scholar?q=Partially%20Safe%20Evolution%20of%20Software%20Product%20Lines

Is found, but has no citations so far. As result, I would expect 0 as the citation count.

**Comment by Kogoro** [comment]
Should be fixed. Tested with the example above.

**Comment by tthuem** [comment]
Nice!
