### ISSUE TITLE
Problems with minor differences in titles for citations

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#26]
First of all, the results are very good now! I actually found almost only wrong entries in Google Scholar and only a minor issue with the following example:

https://scholar.google.de/scholar?q=Variant%20Comparison%20-%20A%20Technique%20for%20Visualizing%20Software%20Variants

Maybe it would be good to compare titles after removing all white-spaces or even other signs that are not letters. What do you think?

The issue has time. Fix it somewhen when there are no urgent thinks to do for FeatureIDE.

**Comment by Kogoro** [comment]
Commit c11a561 adds this functionality. It should bring now a small advantage when using minus, whitespace or any other non-characters specified. Please test it with the now working citation service.

["A word character is a character from a-z, A-Z, 0-9, including the _ (underscore) character."](https://www.w3schools.com/jsref/jsref_regexp_wordchar_non.asp)

**Comment by tthuem** [comment]
Looks good, let's give it a try.
