### ISSUE TITLE
Support for multiple tag lists

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#28]
Currently, we can only give as parameter which BibTeX taglist (e.g., tt-tags or rs-tags) is used for the row with Tags in HTML. It would be nice to use multiple BibTeX taglists for the output.

If multiple taglists are choosen, starting from the second one the name of the taglist should be used as prefix in the following form:

tt-tags = {Bla},
tc-tags = {Blub},

"Bla, tc-Blub" if tt-tags is the first taglist in settings file
"Blub, tt-Bla" if tc-tags is the first taglist in settings file

**Comment by Kogoro** [comment]
The dev branch now contains the support for multiple tags for the single HTML export.
Please check if it solves this issue.

**Comment by tthuem** [comment]
Works great!

**Comment by tthuem** [comment]
Does not work, if the first tag is not existent. Then, the exported taglist is empty.

**Comment by tthuem** [comment]
Would be good if you could continue with this issue. It seems this is the last known bug of MibTeX. :)

**Comment by Kogoro** [comment]
Implemented a check for missing tags

**Comment by tthuem** [comment]
Tags are indeed listed now, but with wrong prefix.

**Comment by tthuem** [comment]
Also, using the HashMap is not a good idea, as it seems to shuffle tag lists in my exports.

**Comment by Kogoro** [comment]
For me the tags are generated and sorted correctly. Do you use the HTML exporter?

**Comment by tthuem** [comment]
For example, the sampling exporter leads to another output order (since your change):

https://github.com/tthuem/MibTeX/blob/dev/MibTeX/src/de/mibtex/export/ExportSampling.java

**Comment by Kogoro** [comment]
The output hasn't changed as far as I can see. Tested the old and the new code. The result of both runs is this:
![unbenannt3](https://user-images.githubusercontent.com/8019776/38619879-781b4c9c-3d9d-11e8-9499-cdcd183bd26d.PNG)

**Comment by tthuem** [comment]
With a hashmap, it may only appear sporadically...
