### ISSUE TITLE
Scholar citations do not work anymore after change to Scholar pages

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#31]
It seems that no citations are found anymore.

**Comment by Kogoro** [comment]
@tthuem Could you try a run for a day so that we can verify the fix?

**Comment by tthuem** [comment]
Does not seem to work.

**Comment by Kogoro** [comment]
Fixed the issue with -2 instead of 0 with 2772d096c222716e1bce508473609106a4ba2185
It should now work like before.

**Comment by tthuem** [comment]
Seems to work now. Thanks!

**Comment by tthuem** [comment]
Opened just by mistake
