### ISSUE TITLE
Improved handling for titles including subtitles in citation service

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#32]
Entries such as SGB05 and KG06 are simply not found as google scholar omits there subtitles. If a paper cannot be found, it should be rather easy to just check the title again, but removing everything starting from ":".

**Comment by Kogoro** [comment]
Implemented a second check without subtitle

**Comment by tthuem** [comment]
Please let me know if I can tryout a new version.

**Comment by Kogoro** [comment]
@tthuem Please try again. Tested it with over 30 entries and seems not unreasonable.

**Comment by tthuem** [comment]
Got the value -2 for the following entries: FKPV:CEC16, KGP:EMSE13, NCB+SEI07, BHJM:STTT07

**Comment by tthuem** [comment]
More examples: [citations.zip](https://github.com/tthuem/MibTeX/files/2206520/citations.zip)

**Comment by Kogoro** [comment]
I integrated the logging into a separate file called problems.csv (s. https://github.com/tthuem/MibTeX/commit/822d57d3c8cc1e666a299b49007bef6190d25cce)

Note: For several hours, the citation service worked quite fine until the calls were stopped by a CAPTCHA. Therefore, please check if the dev-robot branch with commit https://github.com/tthuem/MibTeX/commit/47ce47206214e325d6e49f7cd34135c1238191df is of any help.

**Comment by tthuem** [comment]
My export into a single HTML file does not work anymore (on both branches). It seems that my property file is somehow ignored.

**Comment by Kogoro** [comment]
Works on my system and I did not change anything related to the property files. Do you have a error message?
My ini file looks like:
```
[options]
bibtex-dir=\\BibTags\\
main-dir=\\BibTags\\
out-dir-rel=..\\HTML\\
pdf-dir=..\\Library\\
pdf-dir-rel=PDF
tags=sampling-tags
clean=true
citationService=true
citation-dir=\\BibTags\\classification\\
out-format=HTML_NEW
```

**Comment by tthuem** [comment]
Works better now. Experienced problems only with the following keys so far: DDP:EMSE17, M:ICFI07

There is no entry in the problems.csv so far.

**Comment by Kogoro** [comment]
The site does not list any citations for DDP:EMSE17, but for M:ICFI07 it shows a count of one. Will test this specific two entries again.

**Comment by tthuem** [comment]
In both cases the score was -2. If there are no citations I would have expected 0.

**Comment by Kogoro** [comment]
At the moment, we have the following codes:
```
    public final static int UNINITIALIZED = -1;
    
    public final static int NOT_FOUND = -2;
    
    public final static int PROBLEM_OCCURED = -3;
    
    public final static int ROBOT = -4;
```
We can change -2 to 0, if the title is found.

**Comment by tthuem** [comment]
No, that would not help. Please keep the error codes as is.

0 is supposed to say the article has been found but has no citations.

**Comment by Kogoro** [comment]
Sorry, the regex for the title was wrong and therefore the citations were always -2. Now it is 0 again.

**Comment by tthuem** [comment]
Works fine now
