### ISSUE TITLE
Many publications not found at Google scholar (some of which have been found before)

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#33]
Citation -2 instead for actual citation for many entries, which have been correctly found before, including:

DDP:EMSE17
DABW:STTT17
CBA:OOPSLA17
DL:iFM16
HNTS:ISoLA16
MTS+:ICSE16
...

Entries still not found:

MKR+:ICSE16

**Comment by Kogoro** [comment]
Seems that they changed the site again. It should be solved with a new regex for the entries and citations.
