### ISSUE TITLE
Implement actions for titles, authors and citations

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#6]
Clicking on the paper titel should open the PDF. Clicking on an author name should start a google search with the author name (just the single name, not all authors of the paper). Clicking on the number of citations should search for the paper titel in Google scholar (as you do for retrieving the citations).

**Comment by tthuem** [comment]
Opening the PDFs is the only thing keeping me from using the new version. So it would be great if you could start with that.

**Comment by Kogoro** [comment]
Solved in commit ce1e215.
