### ISSUE TITLE
Add a button to open the literature file

### ISSUE THREAD

**Issue by tthuem** [tthuem/MibTeX#7]
It would be great to have a button/link to the source file (literature.bib) on the top of the HTML page.

**Comment by Kogoro** [comment]
Solved with the new Single Export HTML in 88a06ef

**Comment by tthuem** [comment]
The link does not work for me. There are wrong symbols in the path and Firefox does not ask Windows for the default editor. Any ideas how to fix that?

**Comment by Kogoro** [comment]
Tried mimetype text/plain and application/x-BibTeX, but both are not opening correct in chrome (instead it downloads the file).
Another way would be to display the complete file as a popup. it could also be displayed in a separate file (but that would break the single file concept)

**Comment by tthuem** [comment]
Is all not helpful I guess. Then just remove the download link instead.
